### ISSUE TITLE
rabbitmq-autocluster does not function with consul 1.0.0 due to API changes

### ISSUE THREAD

**Issue by RXM307** [rabbitmq/rabbitmq-autocluster#63]
rabbitmq-autocluster does not function with consul 1.0.0 due to API changes, roll back to 0.9.3 and it works as expected

* RabbitMQ version: 3.6.12
* Erlang version: 19.3
* I'm using docker services for both [consul](https://hub.docker.com/r/library/consul/) &[ rabbitmq-autocluster](https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/)

docker stack deploy -c rabbit-cluster.yml rabbit-cluster

rabbit-cluster.yml
```
version: '3'

#customize this with options from
#https://www.consul.io/docs/agent/options.html

services:
  consul:
    hostname: consul
    # image: consul:0.9.3 #Works
    image: consul:1.0.0 # Does not Work
    deploy:
      replicas: 1
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_HTTP_ADDR=0.0.0.0"
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap-expect=1
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -ui
    networks:
      - "consul"
    ports:
      - "8500:8500"
      - "8600:8600"

  rabbit:
    depends_on:
      - "consul"
    environment:
      - AUTOCLUSTER_TYPE=consul
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_SERVICE_TTL=60
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_SVC_ADDR_AUTO=true
      - CONSUL_DEREGISTER_AFTER=60
    networks:
      - "consul"
    image: rabbitmq-autocluster
    ports:
      - "15672:15672"
    tty: true
    command:  sh -c "sleep 20; rabbitmq-server;"

networks:
  consul:
    driver: overlay
```

rabbitmq log reports
“autocluster: Step register_with_backend failed, will conitnue nevertheless. Failure reason: Failed to register in backend: 405.”
 
consul log reports
[ERR] http: Request POST /v1/agent/service/register, error: method POST not allowed from=10.0.1.5:39340

From https://www.consul.io/docs/upgrade-specific.html it appears Consul now requires PUT not POST for /v1/agent/service/register as well as a number of other endpoints.
