### ISSUE TITLE
Cannot get list of discovered service from consul

### ISSUE THREAD

**Issue by sumeetmi2** [rabbitmq/rabbitmq-autocluster#73]
I have a setup where the consul agent is running on my host machine and I am using pivotal/rabbitmq docker image with autocluster on.

My docker compose looks like below
```
version: "2"
services:
   rabbit:
    environment:
      - TCP_PORTS=15672, 5672,25672,4369,8500
      - AUTOCLUSTER_TYPE=consul
      - AUTOCLUSTER_DELAY=60
      - CONSUL_HOST=localhost
      - CONSUL_ACL_TOKEN=b7862315-05fe-4dda-8b13-4f533ec4e205
      - CONSUL_SVC=terracotta_rabbitmq
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_DEREGISTER_AFTER=60
      - AUTOCLUSTER_LOG_LEVEL=debug
      - CONSUL_SVC_ADDR_AUTO=true
      - CONSUL_SVC_ADDR_NODENAME=true
    image: pivotalrabbitmq/rabbitmq-autocluster
    expose:
      - 15672
      - 5672
      - 5671
      - 15671
      - 33431
      - 8300
      - 4369
      - 25672
      - 8500
    tty: true
    network_mode: host
    command:  sh -c "sleep 20; rabbitmq-server;"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Strangely, on the step where it checks for services that are passing on consul, it gets empty list when queried from inside docker autocluster plugin.

```
bit_1_303964dae0b0 | autocluster: GET http://localhost:8500/v1/health/service/terracotta_rabbitmq
rabbit_1_303964dae0b0 | 
rabbit_1_303964dae0b0 | =INFO REPORT==== 9-Jan-2019::07:35:00 ===
rabbit_1_303964dae0b0 | autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
rabbit_1_303964dae0b0 |                              [{"date","Wed, 09 Jan 2019 07:35:00 GMT"},
rabbit_1_303964dae0b0 |                               {"content-length","2"},
rabbit_1_303964dae0b0 |                               {"content-type","application/json"},
rabbit_1_303964dae0b0 |                               {"x-consul-index","26252192"},
rabbit_1_303964dae0b0 |                               {"x-consul-knownleader","true"},
rabbit_1_303964dae0b0 |                               {"x-consul-lastcontact","0"}],
rabbit_1_303964dae0b0 |                              "[]"}}]

```

But when i curl from inside the docker sh, i get the list of services correctly. Because it is not able to identify passing services from consul, the cluster isnt forming.
